services:
  # MySQL Database
  mysql:
    image: mysql:8.0.35
    container_name: laravel_mysql_production
    restart: always
    environment:
      MYSQL_DATABASE: laravel_production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_production_data:/var/lib/mysql
    networks:
      - laravel_network

  # Laravel Application
  app:
    image: ${DOCKER_IMAGE}:latest
    container_name: laravel_app_production
    restart: always
    working_dir: /var/www/html
    ports:
      - "8004:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.production
    networks:
      - laravel_network
    depends_on:
      - mysql

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_production
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - laravel_network
    depends_on:
      - app

volumes:
  mysql_production_data:
    driver: local

networks:
  laravel_network:
    driver: bridge

